export const LANGUAGES = [
  {
    id: 'tamil',
    label: 'Tamil',
    nativeLabel: 'தமிழ்',
    langCode: 'ta-IN',
    memoryCode: 'ta',
    color: '#F97316',
    bgColor: '#FFF7ED',
    borderColor: '#FB923C',
    textClass: 'text-tamil',
    bgClass: 'bg-tamil-light',
    borderClass: 'border-tamil-border',
    flag: '🇮🇳',
  },
  {
    id: 'english',
    label: 'English',
    nativeLabel: 'English',
    langCode: 'en-US',
    memoryCode: 'en',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    borderColor: '#60A5FA',
    textClass: 'text-english',
    bgClass: 'bg-english-light',
    borderClass: 'border-english-border',
    flag: '🇬🇧',
  },
  {
    id: 'mandarin',
    label: 'Mandarin',
    nativeLabel: '普通话',
    langCode: 'zh-CN',
    memoryCode: 'zh',
    color: '#EF4444',
    bgColor: '#FEF2F2',
    borderColor: '#F87171',
    textClass: 'text-mandarin',
    bgClass: 'bg-mandarin-light',
    borderClass: 'border-mandarin-border',
    flag: '🇨🇳',
  },
  {
    id: 'hindi',
    label: 'Hindi',
    nativeLabel: 'हिन्दी',
    langCode: 'hi-IN',
    memoryCode: 'hi',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    borderColor: '#A78BFA',
    textClass: 'text-hindi',
    bgClass: 'bg-hindi-light',
    borderClass: 'border-hindi-border',
    flag: '🇮🇳',
  },
];

export const LANGUAGE_MAP = Object.fromEntries(LANGUAGES.map(l => [l.id, l]));
export const MEMORY_CODE_MAP = Object.fromEntries(LANGUAGES.map(l => [l.memoryCode, l]));
